controller_list:
  - name: fake_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_gripper_controller
    joints:
      - left_finger_1_joint
      - left_finger_2_joint
      - right_finger_1_joint
      - right_finger_2_joint