gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - left_finger_1_joint
     - left_finger_2_joint
     - right_finger_1_joint
     - right_finger_2_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      left_finger_1_joint: {trajectory: 0.1, goal: 0.1}
      left_finger_2_joint: {trajectory: 0.1, goal: 0.1}
      right_finger_1_joint: {trajectory: 0.1, goal: 0.1}
      right_finger_2_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
